### ISSUE TITLE
Missing install_requires for toml(i)

### ISSUE THREAD

**Issue by The-Compiler** [dfm/black_nbconvert#6]
It looks like `black_nbconvert` uses `toml`, but the `setup.py` doesn't specify it in `install_requires`. Thus, an install in a clean venv fails:

```pytb
$ black_nbconvert Untitled.ipynb
Traceback (most recent call last):
  File "/home/florian/tmp/.venv/bin/black_nbconvert", line 5, in <module>
    from black_nbconvert import main
  File "/home/florian/tmp/.venv/lib/python3.9/site-packages/black_nbconvert.py", line 10, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
```

**Comment by dfm** [comment]
Yes - this was changed in v21.7b0 of black and was fixed moments ago in v0.3.0 of black_nbconvert.
